### ISSUE TITLE
Inherit Color

### ISSUE THREAD

**Issue by kaydwithers** [jxnblk/microicon#12]
Sorry if this is covered somewhere, I couldn't find anything in the docs. Is it possible to inherit a color? 

Something like 
`https://icon.now.sh/chevron/16/currentcolor`

or should `fill='currentColor'` be enabled by default?

**Comment by equinusocio** [comment]
Try `https://icon.now.sh/chevron/16/inherit` and set color to the parent.

**Comment by jxnblk** [comment]
If you're using the URL in an `<img>` tag, SVGs are not inline in the HTML and won't pick up  or inherit the document's styles. You'd have to install the package as an npm dependency to do what you're describing. Let me know if that doesn't make sense
